apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- pairs:
    release: developement
  includeSelectors: true
configMapGenerator:
- name: kiada-env
  behavior: replace
  envs:
  - kiada.dev.env
images:
- name: docker.io/luksa/kiada
  newTag: "0.9"
replicas:
- name: kiada
  count: 1
resources:
- ../../base
