apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- pairs:
    release: production
  includeSelectors: true
configMapGenerator:
- name: kiada-env
  behavior: replace
  envs:
  - kiada.prod.env
nameSuffix: -prod
resources:
- ../../base
patches:
- target:
    kind: Ingress
    name: kiada
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: kiada.libralight.dev
