apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
labels:
- pairs:
    app: kiada
  includeSelectors: true
configMapGenerator:
- name: kiada-env
  envs:
  - kiada.env
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
